/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cbi.frames;

import br.com.cbi.listeners.Listener_Main;
import br.com.cbi.util.ManipulaFrames;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author tiago.teixeira
 */
public final class Form_Main extends ManipulaFrames {

    private static final long serialVersionUID = -419029088399611882L;
    private final Listener_Main listener;

    /**
     * Creates new form Main_Form
     */
    public Form_Main() {
        setImageIcon();
        initComponents();
        stateForm();
        startStatusBar();
        listener = new Listener_Main(this);
        getMenuList();
    }

    private void stateForm() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void startStatusBar() {
        statusBar.startStatusBar(this);
    }

    public List<JMenuItem> getMenuList() {
        List<JMenuItem> lista = new ArrayList();
        forMenu(menuBar.getComponents(), lista);
        return lista;
    }

    private void forMenu(Component[] components, List<JMenuItem> lista) {
        for (Component comp : components) {
            if (comp instanceof JMenu) {
                JMenu menu = (JMenu) comp;
                for (Component a : menu.getMenuComponents()) {
                    if (a instanceof JMenu) {
                        JMenu m = (JMenu) a;
                        forMenu(m.getMenuComponents(), lista);
                    } else if (a instanceof JMenuItem) {
                        JMenuItem i = (JMenuItem) a;
                        lista.add(i);
                    }
                }
            } else if (comp instanceof JMenuItem) {
                JMenuItem i = (JMenuItem) comp;
                lista.add(i);
            }
        }
    }

    public JMenuItem getItemFechar() {
        return itemFechar;
    }

    public JMenuItem getItemGerenciadorRelatorios() {
        return itemGerenciadorRelatorios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        statusBar = new br.com.cbi.beans.JStatusBarCBI();
        menuBar = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemLogout = new javax.swing.JMenuItem();
        itemFechar = new javax.swing.JMenuItem();
        menuGestao = new javax.swing.JMenu();
        Atendimento = new javax.swing.JMenuItem();
        itemRelatorios = new javax.swing.JMenu();
        itemGerenciadorRelatorios = new javax.swing.JMenuItem();
        itemPesquisa = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CBI - Sistema de Gestão Integrada");
        setName("main_form"); // NOI18N

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );

        menuArquivo.setText("Arquivo");

        itemLogout.setText("Logout");
        itemLogout.setActionCommand("logout");
        menuArquivo.add(itemLogout);

        itemFechar.setText("Fechar");
        itemFechar.setActionCommand("fechar");
        menuArquivo.add(itemFechar);

        menuBar.add(menuArquivo);

        menuGestao.setText("Gestão");

        Atendimento.setText("Atendimento");
        Atendimento.setActionCommand("atendimento");
        menuGestao.add(Atendimento);

        menuBar.add(menuGestao);

        itemRelatorios.setText("Relatórios");

        itemGerenciadorRelatorios.setText("Gerenciador de Relatórios");
        itemGerenciadorRelatorios.setActionCommand("reportManager");
        itemRelatorios.add(itemGerenciadorRelatorios);

        menuBar.add(itemRelatorios);

        itemPesquisa.setText("Pesquisa");
        menuBar.add(itemPesquisa);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Atendimento;
    private javax.swing.JMenuItem itemFechar;
    private javax.swing.JMenuItem itemGerenciadorRelatorios;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JMenu itemPesquisa;
    private javax.swing.JMenu itemRelatorios;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuGestao;
    private javax.swing.JPanel panelMain;
    private br.com.cbi.beans.JStatusBarCBI statusBar;
    // End of variables declaration//GEN-END:variables
}
